version: "3"

services:
  jenkins:
    user: jenkins      
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
     - 8080:8080
     - 5000:5000
    volumes:
      - /home/data/jenkins:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
    
  sonar:
    image: sonarqube:latest
    container_name: sonar
    ports:
      - 9000:9000
    volumes:
      - /home/data/sonar:/opt/sonarqube/data
    restart: on-failure

mysqldb:
  container_name: mysqldb
  image: mysql:8
  restart: unless-stopped
  environment:
    MYSQL_ROOT_PASSWORD: root
  ports:
    - 3306:3306
  volumes:
    - /home/mysqldata:/var/lib/mysql

spring_app:
  image: spring-image
  container_name: spring-image
  restart: unless-stopped
  ports:
    - 9090:9090
  depends_on:
    - mysqldb



#   nexus:
#     image: sonatype/nexus3:latest
#     container_name: nexus
#     ports:
#       - 8081:8081
#     volumes:
#       - /home/data/nexus:/sonatype-work
#     restart: on-failure
